[package]
name = "chat-with-codellama"
version = "0.1.0"
edition = "2021"

[dependencies]
chat-prompts = "0.1"
endpoints = "0.1"
wasi-nn = { git = "https://github.com/second-state/wasmedge-wasi-nn", branch = "ggml" }
clap = "4.4.6"
once_cell = "1.18"
