[package]
name = "llama-simple"
version = "0.14.16"
edition = "2021"

[dependencies]
wasmedge-wasi-nn.workspace = true
clap.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
